name: Update Data and Deploy to GitHub Pages

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes

permissions:
  contents: write
  pages: write

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Set environment variables
      - name: Set environment variables
        run: |
          echo "API_TOKEN=${{ env.API_TOKEN }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_PAGE_ID=${{ env.NEXT_PUBLIC_PAGE_ID }}" >> $GITHUB_ENV
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          NEXT_PUBLIC_PAGE_ID: ${{ secrets.NEXT_PUBLIC_PAGE_ID }}

      # Step 5: Run the fetch data script
      - name: Fetch data from Graph API
        run: node src/app/api/fetchData/route.js

      # Step 6: Build the Next.js app
      - name: Build the site
        run: |
          npm run build
          npm run export

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
